### ISSUE TITLE
Pull module name out into its own type so we can enforce wapm2pirita's assumptions

### ISSUE THREAD

**Issue by Michael-F-Bryan** [wasmerio/wasmer-toml#10]
On wapm.io, the [adamz](https://wapm.io/adamz)/[quickjs](https://wapm.io/adamz/quickjs) package uses `adamz/quickjs` as its module name. 

<details>
<summary>wapm.toml file</summary>

```toml
[package]
name = "adamz/quickjs"
version = "0.20210327.0"
description = "QuickJS is a small and embeddable JavaScript engine. It supports the ES2019 specification including modules, asynchronous generators and proxies."
repository = "https://github.com/saghul/wasi-lab"
homepage = "https://bellard.org/quickjs/"

[[module]]
name = "adamz/quickjs"   # <----------
source = "build/qjs.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.0.0-unstable"

[[command]]
name = "qjs"
module = "adamz/quickjs"

[[command]]
name = "quickjs"
module = "adamz/quickjs"
```
</details>

However, when `wapm2pirita` turns the tarball into a `*.webc` file, we rename the atom to just `quickjs`... However, the manifest still thinks it is called `adamz/quickjs`.

<details>
<summary>Manifest and volumes for the WEBC file according to wapm2pirita</summary>

```console
$ wapm2pirita dump volumes bin.webc
{
  "atoms": [
    {
      "name": "quickjs",
      "offset": 1983,
      "size": 2562768
    }
  ],
  "filesystem": {
    "atom": [],
    "metadata": []
  }
}

$ wapm2pirita dump manifest bin.webc
{
  "package": {
    "wapm": {
      "name": "adamz/quickjs",
      "version": "0.20210327.0",
      "homepage": "https://bellard.org/quickjs/",
      "repository": "https://github.com/saghul/wasi-lab",
      "description": "QuickJS is a small and embeddable JavaScript engine. It supports the ES2019 specification including modules, asynchronous generators and proxies."
    }
  },
  "atoms": {
    "adamz/quickjs": {
      "kind": "https://webc.org/kind/wasm",
      "signature": "sha256:b2KmvFyPjj4SpU4uy8VnTM/hx1+R2OTdbrs/7EIqTWw="
    }
  },
  "commands": {
    "qjs": {
      "runner": "https://webc.org/runner/wasi/command@unstable_",
      "annotations": {
        "wasi": {
          "atom": "adamz/quickjs",                <-----------------
          "package": null,
          "main_args": null
        }
      }
    ...
    }
  }
}
```

</details>

That means anything looking up the particular atom will fail because we're looking for `adamz/quickjs` when we should look for `quickjs`. That causes things like `wasmer-pack` to fail downstream.

```console
$ wasmer-pack show ~/Downloads/quickjs-0.20210327.0.tar.gz
Error: Unable to load the package

Caused by:
    Could not find file "adamz/quickjs": could not find file or directory "adamz" (os error 2)
```

To fix this, we should change `wasmer_pack::Module`'s [`name` field](https://github.com/wasmerio/wasmer-toml/blob/27a9aa62e61a902bd477b01a447dc2fa5d12340c/src/lib.rs#L307) from a `String` to some sort of `ModuleName` type which makes sure the manifest name is valid (e.g. it is an "identifier" that doesn't contain a `/`).

Here are the tarball and `*.webc` files we were testing against:

[quickjs-0.20210327.0.tar.gz](https://github.com/wasmerio/wasmer-toml/files/10318950/quickjs-0.20210327.0.tar.gz)
[quickjs-0.20210327.0.webc.zip](https://github.com/wasmerio/wasmer-toml/files/10318953/quickjs-0.20210327.0.webc.zip)
