### ISSUE TITLE
Allow developers to specify a package's entrypoint command

### ISSUE THREAD

**Issue by Michael-F-Bryan** [wasmerio/wasmer-toml#15]
The `wasmer.toml` format doesn't give package developers a way to specify the entrypoint command, so code turning it into a `webc` manifest has to [guess](https://github.com/wasmerio/pirita/blob/17786666f3b08ea1d30067beb6d9460d3a0216fc/crates/webc/src/wasmer_package/manifest.rs#L609-L619):

```rs
/// Infer the package's entrypoint.
///
/// there is no way to explicitly specify an entrypoint in a
/// `wasmer.toml` file. If there is exactly one command, we'll use that,
/// otherwise the entrypoint will be left unspecified.
fn entrypoint(manifest: &WasmerManifest) -> Option<String> {
    match manifest.command.as_deref() {
        Some([only_command]) => Some(only_command.get_name()),
        _ => None,
    }
}
```

We should allow package developers to specify the entrypoint so downstream users don't need to do `wasmer run my/package --command=some-command` every time.

## Possible Syntax

Given a package with multiple commands, there are a couple different ways the `entrypoint` could be specified.

### Option 1 - put it in `[package]`

```toml
[package]
name = "sharrattj/bash"
version = "1.2.3"
entrypoint = "bash"

[[module]]
name = "bash"
source = "./bash.wasm"
abi = "wasi"

[[command]]
name = "bash"
module = "bash"

[[command]]
name = "sh"
module = "bash"
```

### Option 2 - put it in the command

```toml
[package]
name = "sharrattj/bash"
version = "1.2.3"

[[module]]
name = "bash"
source = "./bash.wasm"
abi = "wasi"

[[command]]
name = "bash"
module = "bash"
entrypoint = true

[[command]]
name = "sh"
module = "bash"
```

### Option 3 - create a separate section

```toml
[package]
name = "sharrattj/bash"
version = "1.2.3"

[[module]]
name = "bash"
source = "./bash.wasm"
abi = "wasi"

[[command]]
name = "bash"
module = "bash"

[[command]]
name = "sh"
module = "bash"

[defaults]
entrypoint = "bash"
```
