### ISSUE TITLE
Add syntax for specifying a command that uses a dependency's atom

### ISSUE THREAD

**Issue by Michael-F-Bryan** [wasmerio/wasmer-toml#21]
Imagine you have a package containing some Python scripts. Rather than embedding a copy of the Python interpreter, you would prefer to use a Python package as a dependency and just add your `*.py` files to the package.

Your `wasmer.toml` might look like this:

```toml
[package]
name = "my/python-program"
version = "1.2.3"

[dependencies]
"wasmer/python" = "3.12"

[fs]
"/app/src" = "./src"
"/app/.env" = "./.env/" # Bundle the virtualenv

[[command]]
name = "script"
module = "wasmer/python:python" # The "python" atom from "wasmer/python"
runner = "wasi"

[annotations.wasi]
args = ["/app/main.py", "with", "--extra=flags"]
env = ["PYTHON_PATH=/app/.env:/etc/python3.12/site-packages"] # Make our virtualenv accessible
```

To make this use case work, we need a way to express `module = "wasmer/python:python"`.
