### ISSUE TITLE
Nested paths don't work as expected

### ISSUE THREAD

**Issue by dynamite-bud** [wasmerio/wasmer-toml#30]
## Observed Error
When working with nested paths such as:

```toml
[package]
name = "dynamite-bud/py-worker-test-1"
version = "0.1.3"
description = "dynamite-bud/py-worker-test-1 py worker"

[dependencies]
"wasmer/python" = "^3.12.6"

[fs]
"/app/src" = "./src"

[[command]]
name = "script"
module = "wasmer/python:python"
runner = "wasi"

[command.annotations.wasi]
main-args = ["/app/src/main.py"]
```

#### Error
Running it with `wasmer run .` results in an error:
`script: can't open file '/app/src/main.py': [Errno 44] No such file or directory`

## Expected Behaviour
Ideal toml file that **works**
```toml
[package]
name = "dynamite-bud/py-worker-test-1"
version = "0.1.3"
description = "dynamite-bud/py-worker-test-1 py worker"

[dependencies]
"wasmer/python" = "^3.12.6"

[fs]
"/src" = "./src"

[[command]]
name = "script"
module = "wasmer/python:python"
runner = "wasi"

[command.annotations.wasi]
main-args = ["/src/main.py"]
```

The above 👆🏼 works
